[plugin]
prefix = 'pl'
body = """
return function(manager)
\tmanager.add({
\t\tid = "$1",
\t\turl = "$2",$3
\t})
end
"""

[plugin_config]
prefix = 'plc'
body = """
local function config()
\t$1
end

return function(manager)
\tmanager.add({
\t\tid = "$2",
\t\turl = "$3",$4
\t\tconfig = config,
\t})
end
"""

[plugin_lazy]
prefix = 'pll'
body = """
local lazyload = require("utils.lazyload")

return function(manager)
\tmanager.add({
\t\tid = "$1",
\t\turl = "$2",$3
\t})
\tlazyload.$4
end
"""

[plugin_config_lazy]
prefix = 'plcl'
body = """
local lazyload = require("utils.lazyload")

local function config()
\t$1
end

return function(manager)
\tmanager.add({
\t\tid = "$2",
\t\turl = "$3",$4
\t\tconfig = config,
\t})
\tlazyload.$5
end
"""
